// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/admin/tokens/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/tokens">> = Specific
  const handler = {} as typeof import("../../src/app/admin/tokens/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/fii-dii/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fii-dii">> = Specific
  const handler = {} as typeof import("../../src/app/fii-dii/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/nifty/option-chain/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/nifty/option-chain">> = Specific
  const handler = {} as typeof import("../../src/app/nifty/option-chain/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/sensex/option-chain/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sensex/option-chain">> = Specific
  const handler = {} as typeof import("../../src/app/sensex/option-chain/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../src/app/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/subscription/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/subscription">> = Specific
  const handler = {} as typeof import("../../src/app/subscription/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/upstox/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/upstox/login">> = Specific
  const handler = {} as typeof import("../../src/app/upstox/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/upstox-token/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/upstox-token">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/upstox-token/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/signup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/signup">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/signup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/cash-gainers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/cash-gainers">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/cash-gainers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/cash-losers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/cash-losers">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/cash-losers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/demand-stocks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/demand-stocks">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/demand-stocks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/futures-gainers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/futures-gainers">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/futures-gainers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/futures-losers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/futures-losers">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/futures-losers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/intraday-stocks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/intraday-stocks">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/intraday-stocks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/top-buy/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/top-buy">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/top-buy/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/nifty/option-chain/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/nifty/option-chain">> = Specific
  const handler = {} as typeof import("../../src/app/api/nifty/option-chain/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/nifty/pcr/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/nifty/pcr">> = Specific
  const handler = {} as typeof import("../../src/app/api/nifty/pcr/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/upstox/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/upstox/callback">> = Specific
  const handler = {} as typeof import("../../src/app/api/upstox/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/upstox/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/upstox/login">> = Specific
  const handler = {} as typeof import("../../src/app/api/upstox/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/upstox/ltp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/upstox/ltp">> = Specific
  const handler = {} as typeof import("../../src/app/api/upstox/ltp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/upstox/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/upstox/session">> = Specific
  const handler = {} as typeof import("../../src/app/api/upstox/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
